server {
    listen 80;
    resolver 127.0.0.11 valid=10s;
    client_max_body_size 120M;
    sendfile on;
    gzip on;
    gzip_types text/plain application/json application/octet-stream;
    gzip_vary on;
    gunzip on;
    access_log off;

        # Reverse Proxy for API
        location /api/ {
            proxy_pass http://server:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Reverse Proxy for Frontend
        location / {
            proxy_pass http://client:4173;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # thumbnails location
        location /thumbnails/ {
            internal;
            # important to add the trailing slash
            alias /thumbnails/;
            add_header X-Debug-Original-URI $uri;
            add_header X-Debug-Destination $request_filename;
        }

        # add location for each StorageBackend below:

        # location /<StorageBackend.Key>/ {
        #     internal;
        #     # important to add the trailing slash
        #     alias <mount_path inside container>;
        #     add_header X-Debug-Original-URI $uri;
        #     add_header X-Debug-Destination $request_filename;
        # }

}
