"""orm baseline

Revision ID: orm_baseline
Revises: 
Create Date: 2026-08-20 11:40:16.424717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'orm_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AnnotationType',
    sa.Column('AnnotationTypeID', sa.Integer(), nullable=False),
    sa.Column('AnnotationTypeName', sa.String(length=45), nullable=False),
    sa.Column('Interpretation', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('AnnotationTypeID'),
    sa.UniqueConstraint('AnnotationTypeName', 'Interpretation', name='AnnotationTypeNameInterpretation_UNIQUE')
    )
    op.create_table('AttributeDefinition',
    sa.Column('AttributeID', sa.Integer(), nullable=False),
    sa.Column('AttributeName', sa.String(length=255), nullable=False),
    sa.Column('AttributeDataType', sa.Enum('String', 'Float', 'Int', 'JSON', name='attributedatatype'), nullable=False),
    sa.PrimaryKeyConstraint('AttributeID'),
    sa.UniqueConstraint('AttributeName', name='uq_AttributeDefinition_AttributeName')
    )
    op.create_table('AuditLog',
    sa.Column('AuditLogID', sa.Integer(), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=False),
    sa.Column('ActorID', sa.Integer(), nullable=True),
    sa.Column('TrustedPath', sa.String(length=255), nullable=True),
    sa.Column('Action', sa.String(length=16), nullable=False),
    sa.Column('Entity', sa.String(length=64), nullable=False),
    sa.Column('EntityID', sa.String(length=255), nullable=True),
    sa.Column('ProjectID', sa.Integer(), nullable=True),
    sa.Column('Changes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('AuditLogID')
    )
    op.create_index('ix_AuditLog_ActorID', 'AuditLog', ['ActorID'], unique=False)
    op.create_index('ix_AuditLog_Timestamp', 'AuditLog', ['Timestamp'], unique=False)
    op.create_table('Contact',
    sa.Column('ContactID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Institute', sa.String(length=255), nullable=True),
    sa.Column('Orcid', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ContactID')
    )
    op.create_index('NameEmailInstitute_UNIQUE', 'Contact', ['Name', 'Email', 'Institute'], unique=True)
    op.create_table('Creator',
    sa.Column('CreatorID', sa.Integer(), nullable=False),
    sa.Column('CreatorName', sa.String(length=45), nullable=False),
    sa.Column('EmployeeIdentifier', sa.String(length=255), nullable=True),
    sa.Column('IsHuman', sa.Boolean(), nullable=False),
    sa.Column('Path', sa.String(length=80), nullable=True),
    sa.Column('Version', sa.Integer(), nullable=True),
    sa.Column('Description', sa.String(length=1000), nullable=True),
    sa.Column('Role', sa.Integer(), nullable=True),
    sa.Column('IsAdmin', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('Inactive', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('Password', sa.BINARY(length=32), nullable=True),
    sa.Column('PasswordHash', sa.String(length=255), nullable=True),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('CreatorID'),
    sa.UniqueConstraint('CreatorName')
    )
    op.create_table('DeviceModel',
    sa.Column('DeviceModelID', sa.Integer(), nullable=False),
    sa.Column('Manufacturer', sa.String(length=45), nullable=False),
    sa.Column('ManufacturerModelName', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('DeviceModelID')
    )
    op.create_index('ManufacturerManufacturerModelName_UNIQUE', 'DeviceModel', ['Manufacturer', 'ManufacturerModelName'], unique=True)
    op.create_table('Feature',
    sa.Column('FeatureID', sa.Integer(), nullable=False),
    sa.Column('FeatureName', sa.String(length=60), nullable=False),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('FeatureID'),
    sa.UniqueConstraint('FeatureName')
    )
    op.create_table('FormSchema',
    sa.Column('FormSchemaID', sa.Integer(), nullable=False),
    sa.Column('SchemaName', sa.String(length=255), nullable=False),
    sa.Column('Schema', mysql.JSON(), nullable=True),
    sa.Column('EntityType', sa.Enum('Patient', 'Study', 'Eye', 'StudyEye', 'ImageInstance', name='entitytype'), nullable=True),
    sa.PrimaryKeyConstraint('FormSchemaID'),
    sa.UniqueConstraint('SchemaName')
    )
    op.create_table('Modality',
    sa.Column('ModalityID', sa.Integer(), nullable=False),
    sa.Column('ModalityTag', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('ModalityID'),
    sa.UniqueConstraint('ModalityTag')
    )
    op.create_table('Model',
    sa.Column('ModelID', sa.Integer(), nullable=False),
    sa.Column('ModelName', sa.String(length=255), nullable=False),
    sa.Column('Version', sa.String(length=255), nullable=False),
    sa.Column('ModelType', sa.Enum('segmentation', 'attributes', name='modelkind'), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ModelID'),
    sa.UniqueConstraint('ModelName', 'Version')
    )
    op.create_table('Scan',
    sa.Column('ScanID', sa.Integer(), nullable=False),
    sa.Column('ScanMode', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('ScanID'),
    sa.UniqueConstraint('ScanMode')
    )
    op.create_table('SourceInfo',
    sa.Column('SourceInfoID', sa.Integer(), nullable=False),
    sa.Column('SourceName', sa.String(length=64), nullable=False),
    sa.Column('SourcePath', sa.String(length=250), nullable=False),
    sa.Column('ThumbnailPath', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('SourceInfoID'),
    sa.UniqueConstraint('SourceName'),
    sa.UniqueConstraint('SourcePath'),
    sa.UniqueConstraint('ThumbnailPath')
    )
    op.create_table('StorageBackend',
    sa.Column('StorageBackendID', sa.Integer(), nullable=False),
    sa.Column('Key', sa.String(length=256), nullable=False),
    sa.Column('Kind', sa.String(length=256), nullable=False),
    sa.Column('Config', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('StorageBackendID'),
    sa.UniqueConstraint('Key')
    )
    op.create_table('TaskDefinition',
    sa.Column('TaskDefinitionID', sa.Integer(), nullable=False),
    sa.Column('TaskDefinitionName', sa.String(length=256), nullable=False),
    sa.Column('TaskConfig', sa.JSON(), nullable=True),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('TaskDefinitionID')
    )
    op.create_table('AttributesModel',
    sa.Column('ModelID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ModelID'], ['Model.ModelID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ModelID')
    )
    op.create_table('CompositeFeature',
    sa.Column('ParentFeatureID', sa.Integer(), nullable=False),
    sa.Column('ChildFeatureID', sa.Integer(), nullable=False),
    sa.Column('FeatureIndex', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ChildFeatureID'], ['Feature.FeatureID'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ParentFeatureID'], ['Feature.FeatureID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ParentFeatureID', 'ChildFeatureID', 'FeatureIndex')
    )
    op.create_index('fk_CompositeFeature_ChildFeature1_idx', 'CompositeFeature', ['ChildFeatureID'], unique=False)
    op.create_index('fk_CompositeFeature_ParentFeature1_idx', 'CompositeFeature', ['ParentFeatureID'], unique=False)
    op.create_table('DeviceInstance',
    sa.Column('DeviceInstanceID', sa.Integer(), nullable=False),
    sa.Column('DeviceModelID', sa.Integer(), nullable=False),
    sa.Column('SerialNumber', mysql.TEXT(), nullable=True),
    sa.Column('Description', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['DeviceModelID'], ['DeviceModel.DeviceModelID'], ),
    sa.PrimaryKeyConstraint('DeviceInstanceID')
    )
    op.create_index('DeviceModelIDDescription_UNIQUE', 'DeviceInstance', ['DeviceModelID', 'Description'], unique=True)
    op.create_table('Project',
    sa.Column('ProjectID', sa.Integer(), nullable=False),
    sa.Column('ProjectName', sa.String(length=255), nullable=False),
    sa.Column('External', sa.Enum('Y', 'N', 'M', name='externalenum'), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('ContactID', sa.Integer(), nullable=True),
    sa.Column('DOI', sa.String(length=255), nullable=True),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ContactID'], ['Contact.ContactID'], ),
    sa.PrimaryKeyConstraint('ProjectID'),
    sa.UniqueConstraint('ProjectName')
    )
    op.create_index('fk_Project_Contact1_idx', 'Project', ['ContactID'], unique=False)
    op.create_table('SegmentationModel',
    sa.Column('ModelID', sa.Integer(), nullable=False),
    sa.Column('FeatureID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['FeatureID'], ['Feature.FeatureID'], ),
    sa.ForeignKeyConstraint(['ModelID'], ['Model.ModelID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ModelID')
    )
    op.create_table('Tag',
    sa.Column('TagID', sa.Integer(), nullable=False),
    sa.Column('TagName', sa.String(length=256), nullable=False),
    sa.Column('TagType', sa.Enum('Study', 'ImageInstance', 'Annotation', 'Segmentation', 'FormAnnotation', name='tagtype'), nullable=False),
    sa.Column('TagDescription', sa.String(length=256), nullable=False),
    sa.Column('CreatorID', sa.Integer(), nullable=False),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['CreatorID'], ['Creator.CreatorID'], ),
    sa.PrimaryKeyConstraint('TagID'),
    sa.UniqueConstraint('TagName', 'TagType', name='Tag')
    )
    op.create_index('fk_Tag_Creator1_idx', 'Tag', ['CreatorID'], unique=False)
    op.create_table('Task',
    sa.Column('TaskID', sa.Integer(), nullable=False),
    sa.Column('TaskName', sa.String(length=256), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('CreatorID', sa.Integer(), nullable=True),
    sa.Column('ContactID', sa.Integer(), nullable=True),
    sa.Column('TaskDefinitionID', sa.Integer(), nullable=False),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('TaskState', sa.Enum('NotStarted', 'Busy', 'Finished', 'Aborted', 'Archived', name='taskstate'), nullable=False),
    sa.ForeignKeyConstraint(['ContactID'], ['Contact.ContactID'], ),
    sa.ForeignKeyConstraint(['CreatorID'], ['Creator.CreatorID'], ),
    sa.ForeignKeyConstraint(['TaskDefinitionID'], ['TaskDefinition.TaskDefinitionID'], ),
    sa.PrimaryKeyConstraint('TaskID')
    )
    op.create_index('fk_Task_TaskDefinition1_idx', 'Task', ['TaskDefinitionID'], unique=False)
    op.create_index('ix_Task_Creator_TaskDefinition', 'Task', ['CreatorID', 'TaskDefinitionID'], unique=False)
    op.create_table('AttributesModelOutput',
    sa.Column('ModelID', sa.Integer(), nullable=False),
    sa.Column('AttributeID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['AttributeID'], ['AttributeDefinition.AttributeID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ModelID'], ['AttributesModel.ModelID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ModelID', 'AttributeID')
    )
    op.create_table('CreatorTag',
    sa.Column('TagID', sa.Integer(), nullable=False),
    sa.Column('CreatorID', sa.Integer(), nullable=False),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['CreatorID'], ['Creator.CreatorID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['TagID'], ['Tag.TagID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('TagID', 'CreatorID')
    )
    op.create_index('fk_CreatorTag_Creator1_idx', 'CreatorTag', ['CreatorID'], unique=False)
    op.create_index('fk_CreatorTag_Tag1_idx', 'CreatorTag', ['TagID'], unique=False)
    op.create_table('ModelInput',
    sa.Column('ModelInputID', sa.Integer(), nullable=False),
    sa.Column('ModelID', sa.Integer(), nullable=False),
    sa.Column('InputAttributeID', sa.Integer(), nullable=False),
    sa.Column('InputName', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['InputAttributeID'], ['AttributeDefinition.AttributeID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ModelID'], ['AttributesModel.ModelID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ModelInputID'),
    sa.UniqueConstraint('ModelID', 'InputAttributeID', name='uq_ModelInput_ModelID_InputAttributeID')
    )
    op.create_index('fk_ModelInput_Attribute1_idx', 'ModelInput', ['InputAttributeID'], unique=False)
    op.create_index('fk_ModelInput_Model1_idx', 'ModelInput', ['ModelID'], unique=False)
    op.create_table('Patient',
    sa.Column('PatientID', sa.Integer(), nullable=False),
    sa.Column('PatientIdentifier', sa.String(length=255), nullable=False),
    sa.Column('BirthDate', sa.Date(), nullable=True),
    sa.Column('Sex', sa.Enum('M', 'F', name='sexenum'), nullable=True),
    sa.Column('ProjectID', sa.Integer(), nullable=False),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ProjectID'], ['Project.ProjectID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('PatientID')
    )
    op.create_index('ProjectIDPatientIdentifier_UNIQUE', 'Patient', ['ProjectID', 'PatientIdentifier'], unique=True)
    op.create_index('fk_Patient_Project1_idx', 'Patient', ['ProjectID'], unique=False)
    op.create_index('ix_Patient_PatientIdentifier', 'Patient', ['PatientIdentifier'], unique=False)
    op.create_index('ix_Patient_Project_Sex_BirthDate', 'Patient', ['ProjectID', 'Sex', 'BirthDate'], unique=False)
    op.create_table('ProjectMember',
    sa.Column('CreatorID', sa.Integer(), nullable=False),
    sa.Column('ProjectID', sa.Integer(), nullable=False),
    sa.Column('Role', sa.Enum('read_only', 'grader', 'project_admin', name='projectrole'), nullable=False),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['CreatorID'], ['Creator.CreatorID'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ProjectID'], ['Project.ProjectID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('CreatorID', 'ProjectID')
    )
    op.create_table('SubTask',
    sa.Column('SubTaskID', sa.Integer(), nullable=False),
    sa.Column('TaskID', sa.Integer(), nullable=False),
    sa.Column('CreatorID', sa.Integer(), nullable=True),
    sa.Column('Comments', sa.Text(), nullable=True),
    sa.Column('TaskState', sa.Enum('NotStarted', 'Busy', 'Ready', name='subtaskstate'), nullable=False),
    sa.ForeignKeyConstraint(['CreatorID'], ['Creator.CreatorID'], ),
    sa.ForeignKeyConstraint(['TaskID'], ['Task.TaskID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SubTaskID')
    )
    op.create_index('fk_SubTask_Creator1_idx', 'SubTask', ['CreatorID'], unique=False)
    op.create_index('fk_SubTask_Task1_idx', 'SubTask', ['TaskID'], unique=False)
    op.create_index('ix_SubTask_TaskState_Creator', 'SubTask', ['TaskState', 'CreatorID'], unique=False)
    op.create_table('Study',
    sa.Column('StudyID', sa.Integer(), nullable=False),
    sa.Column('PatientID', sa.Integer(), nullable=False),
    sa.Column('StudyRound', sa.Integer(), nullable=True),
    sa.Column('StudyDescription', sa.String(length=64), nullable=True),
    sa.Column('StudyDate', sa.Date(), nullable=False),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['PatientID'], ['Patient.PatientID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('StudyID')
    )
    op.create_index('PatientIDStudyDate_UNIQUE', 'Study', ['PatientID', 'StudyDate'], unique=True)
    op.create_index('StudyDate_idx', 'Study', ['StudyDate'], unique=False)
    op.create_index('fk_Study_Patient1_idx', 'Study', ['PatientID'], unique=False)
    op.create_index('ix_Study_PatientID_StudyRound', 'Study', ['PatientID', 'StudyRound'], unique=False)
    op.create_index('ix_Study_StudyRound_StudyDate', 'Study', ['StudyRound', 'StudyDate'], unique=False)
    op.create_table('Series',
    sa.Column('SeriesID', sa.Integer(), nullable=False),
    sa.Column('StudyID', sa.Integer(), nullable=False),
    sa.Column('SeriesNumber', sa.Integer(), nullable=True),
    sa.Column('SeriesInstanceUid', sa.String(length=64), nullable=True),
    sa.Column('StudyInstanceUid', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['StudyID'], ['Study.StudyID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SeriesID'),
    sa.UniqueConstraint('SeriesInstanceUid')
    )
    op.create_index('StudyInstanceUidSeriesInstanceUid_UNIQUE', 'Series', ['StudyInstanceUid', 'SeriesInstanceUid'], unique=True)
    op.create_index('fk_Series_Study1_idx', 'Series', ['StudyID'], unique=False)
    op.create_index('ix_Series_StudyID_SeriesNumber', 'Series', ['StudyID', 'SeriesNumber'], unique=False)
    op.create_index('ix_Series_StudyID_StudyInstanceUid', 'Series', ['StudyID', 'StudyInstanceUid'], unique=False)
    op.create_table('StudyTag',
    sa.Column('TagID', sa.Integer(), nullable=False),
    sa.Column('StudyID', sa.Integer(), nullable=False),
    sa.Column('CreatorID', sa.Integer(), nullable=False),
    sa.Column('Comment', sa.String(length=256), nullable=True),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['CreatorID'], ['Creator.CreatorID'], ),
    sa.ForeignKeyConstraint(['StudyID'], ['Study.StudyID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['TagID'], ['Tag.TagID'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('TagID', 'StudyID')
    )
    op.create_index('fk_StudyTag_Creator1_idx', 'StudyTag', ['CreatorID'], unique=False)
    op.create_index('fk_StudyTag_Study1_idx', 'StudyTag', ['StudyID'], unique=False)
    op.create_index('fk_StudyTag_Tag1_idx', 'StudyTag', ['TagID'], unique=False)
    op.create_index('ix_StudyTag_Study_Tag', 'StudyTag', ['StudyID', 'TagID'], unique=False)
    op.create_table('ImageInstance',
    sa.Column('ImageInstanceID', sa.Integer(), nullable=False),
    sa.Column('PublicID', sa.CHAR(length=12), nullable=False),
    sa.Column('SeriesID', sa.Integer(), nullable=False),
    sa.Column('SourceInfoID', sa.Integer(), nullable=True),
    sa.Column('DeviceInstanceID', sa.Integer(), nullable=False),
    sa.Column('ModalityID', sa.Integer(), nullable=True),
    sa.Column('ScanID', sa.Integer(), nullable=True),
    sa.Column('Modality', sa.Enum('AdaptiveOptics', 'ColorFundus', 'ColorFundusStereo', 'RedFreeFundus', 'ExternalEye', 'LensPhotograph', 'Ophthalmoscope', 'Autofluorescence', 'FluoresceinAngiography', 'ICGA', 'InfraredReflectance', 'BlueReflectance', 'GreenReflectance', 'OCT', 'OCTA', name='modality'), nullable=True),
    sa.Column('SOPInstanceUid', sa.String(length=64), nullable=True),
    sa.Column('SOPClassUid', sa.String(length=64), nullable=True),
    sa.Column('PhotometricInterpretation', sa.String(length=64), nullable=True),
    sa.Column('SamplesPerPixel', sa.Integer(), nullable=True),
    sa.Column('Rows_y', sa.Integer(), nullable=True),
    sa.Column('Columns_x', sa.Integer(), nullable=True),
    sa.Column('NrOfFrames', sa.Integer(), nullable=True),
    sa.Column('SliceThickness', sa.Float(), nullable=True),
    sa.Column('ResolutionAxial', sa.Float(), nullable=True),
    sa.Column('ResolutionHorizontal', sa.Float(), nullable=True),
    sa.Column('ResolutionVertical', sa.Float(), nullable=True),
    sa.Column('HorizontalFieldOfView', sa.Float(), nullable=True),
    sa.Column('Laterality', sa.Enum('L', 'R', name='laterality'), nullable=True),
    sa.Column('DICOMModality', sa.Enum('OP', 'OPT', 'SC', name='modalitytype'), nullable=True),
    sa.Column('AnatomicRegion', sa.Integer(), nullable=True),
    sa.Column('ETDRSField', sa.Enum('F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', name='etdrsfield'), nullable=True),
    sa.Column('Angiography', sa.Integer(), nullable=True),
    sa.Column('AcquisitionDateTime', sa.DateTime(), nullable=True),
    sa.Column('PupilDilated', sa.Boolean(), nullable=True),
    sa.Column('DatasetIdentifier', sa.String(length=256), nullable=False),
    sa.Column('AltDatasetIdentifier', sa.String(length=256), nullable=True),
    sa.Column('ThumbnailPath', sa.String(length=256), nullable=True),
    sa.Column('OldPath', sa.String(length=256), nullable=True),
    sa.Column('FDAIdentifier', sa.Integer(), nullable=True),
    sa.Column('Inactive', sa.Boolean(), nullable=False),
    sa.Column('CFROI', mysql.JSON(), nullable=True),
    sa.Column('CFKeypoints', mysql.JSON(), nullable=True),
    sa.Column('CFQuality', sa.Float(), nullable=True),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('DateModified', sa.DateTime(), nullable=True),
    sa.Column('DatePreprocessed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['DeviceInstanceID'], ['DeviceInstance.DeviceInstanceID'], ),
    sa.ForeignKeyConstraint(['ModalityID'], ['Modality.ModalityID'], ),
    sa.ForeignKeyConstraint(['ScanID'], ['Scan.ScanID'], ),
    sa.ForeignKeyConstraint(['SeriesID'], ['Series.SeriesID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['SourceInfoID'], ['SourceInfo.SourceInfoID'], ),
    sa.PrimaryKeyConstraint('ImageInstanceID'),
    sa.UniqueConstraint('PublicID')
    )
    op.create_index('SOPInstanceUid_UNIQUE', 'ImageInstance', ['SOPInstanceUid'], unique=True)
    op.create_index('fk_ImageInstance_DeviceInstance1_idx', 'ImageInstance', ['DeviceInstanceID'], unique=False)
    op.create_index('fk_ImageInstance_Modality1_idx', 'ImageInstance', ['ModalityID'], unique=False)
    op.create_index('fk_ImageInstance_Scan1_idx', 'ImageInstance', ['ScanID'], unique=False)
    op.create_index('fk_ImageInstance_Series1_idx', 'ImageInstance', ['SeriesID'], unique=False)
    op.create_index('fk_ImageInstance_Series_Inactive1_idx', 'ImageInstance', ['SeriesID', 'Inactive'], unique=False)
    op.create_index('fk_ImageInstance_SourceInfo1_idx', 'ImageInstance', ['SourceInfoID'], unique=False)
    op.create_index('ix_ImageInstance_Modality_Inactive_ETDRSField', 'ImageInstance', ['Modality', 'Inactive', 'ETDRSField'], unique=False)
    op.create_index('ix_ImageInstance_Modality_Inactive_Laterality', 'ImageInstance', ['Modality', 'Inactive', 'Laterality'], unique=False)
    op.create_table('Annotation',
    sa.Column('AnnotationID', sa.Integer(), nullable=False),
    sa.Column('PatientID', sa.Integer(), nullable=False),
    sa.Column('StudyID', sa.Integer(), nullable=True),
    sa.Column('SeriesID', sa.Integer(), nullable=True),
    sa.Column('ImageInstanceID', sa.Integer(), nullable=True),
    sa.Column('CreatorID', sa.Integer(), nullable=False),
    sa.Column('FeatureID', sa.Integer(), nullable=False),
    sa.Column('AnnotationTypeID', sa.Integer(), nullable=False),
    sa.Column('AnnotationReferenceID', sa.Integer(), nullable=True),
    sa.Column('Inactive', sa.Boolean(), nullable=False),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['AnnotationReferenceID'], ['Annotation.AnnotationID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['AnnotationTypeID'], ['AnnotationType.AnnotationTypeID'], ),
    sa.ForeignKeyConstraint(['CreatorID'], ['Creator.CreatorID'], ),
    sa.ForeignKeyConstraint(['FeatureID'], ['Feature.FeatureID'], ),
    sa.ForeignKeyConstraint(['ImageInstanceID'], ['ImageInstance.ImageInstanceID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['PatientID'], ['Patient.PatientID'], ),
    sa.ForeignKeyConstraint(['SeriesID'], ['Series.SeriesID'], ),
    sa.ForeignKeyConstraint(['StudyID'], ['Study.StudyID'], ),
    sa.PrimaryKeyConstraint('AnnotationID')
    )
    op.create_index('fk_Annotation_AnnotationType1_idx', 'Annotation', ['AnnotationTypeID'], unique=False)
    op.create_index('fk_Annotation_Creator1_idx', 'Annotation', ['CreatorID'], unique=False)
    op.create_index('fk_Annotation_Feature1_idx', 'Annotation', ['FeatureID'], unique=False)
    op.create_index('fk_Annotation_ImageInstance1_idx', 'Annotation', ['ImageInstanceID'], unique=False)
    op.create_index('fk_Annotation_Patient1_idx', 'Annotation', ['PatientID'], unique=False)
    op.create_index('fk_Annotation_Series1_idx', 'Annotation', ['SeriesID'], unique=False)
    op.create_index('fk_Annotation_Study1_idx', 'Annotation', ['StudyID'], unique=False)
    op.create_table('FormAnnotation',
    sa.Column('FormAnnotationID', sa.Integer(), nullable=False),
    sa.Column('FormSchemaID', sa.Integer(), nullable=False),
    sa.Column('PatientID', sa.Integer(), nullable=False),
    sa.Column('StudyID', sa.Integer(), nullable=True),
    sa.Column('ImageInstanceID', sa.Integer(), nullable=True),
    sa.Column('Laterality', sa.Enum('L', 'R', name='laterality'), nullable=True),
    sa.Column('CreatorID', sa.Integer(), nullable=False),
    sa.Column('SubTaskID', sa.Integer(), nullable=True),
    sa.Column('FormData', mysql.JSON(), nullable=True),
    sa.Column('FormAnnotationReferenceID', sa.Integer(), nullable=True),
    sa.Column('Inactive', sa.Boolean(), nullable=False),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('DateModified', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['CreatorID'], ['Creator.CreatorID'], ),
    sa.ForeignKeyConstraint(['FormAnnotationReferenceID'], ['FormAnnotation.FormAnnotationID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['FormSchemaID'], ['FormSchema.FormSchemaID'], ),
    sa.ForeignKeyConstraint(['ImageInstanceID'], ['ImageInstance.ImageInstanceID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['PatientID'], ['Patient.PatientID'], ),
    sa.ForeignKeyConstraint(['StudyID'], ['Study.StudyID'], ),
    sa.ForeignKeyConstraint(['SubTaskID'], ['SubTask.SubTaskID'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('FormAnnotationID')
    )
    op.create_index(op.f('ix_FormAnnotation_FormAnnotationReferenceID'), 'FormAnnotation', ['FormAnnotationReferenceID'], unique=False)
    op.create_index('ix_FormAnnotation_FormSchema_Inactive_Creator', 'FormAnnotation', ['FormSchemaID', 'Inactive', 'CreatorID'], unique=False)
    op.create_index('ix_FormAnnotation_Image_Laterality_Inactive', 'FormAnnotation', ['ImageInstanceID', 'Laterality', 'Inactive'], unique=False)
    op.create_index('ix_FormAnnotation_Patient_Study_Inactive', 'FormAnnotation', ['PatientID', 'StudyID', 'Inactive'], unique=False)
    op.create_index('ix_FormAnnotation_SubTask_Inactive', 'FormAnnotation', ['SubTaskID', 'Inactive'], unique=False)
    op.create_table('ImageInstanceTag',
    sa.Column('TagID', sa.Integer(), nullable=False),
    sa.Column('ImageInstanceID', sa.Integer(), nullable=False),
    sa.Column('CreatorID', sa.Integer(), nullable=False),
    sa.Column('Comment', sa.String(length=256), nullable=True),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['CreatorID'], ['Creator.CreatorID'], ),
    sa.ForeignKeyConstraint(['ImageInstanceID'], ['ImageInstance.ImageInstanceID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['TagID'], ['Tag.TagID'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('TagID', 'ImageInstanceID')
    )
    op.create_index('fk_ImageInstanceTag_Creator1_idx', 'ImageInstanceTag', ['CreatorID'], unique=False)
    op.create_index('fk_ImageInstanceTag_ImageInstance1_idx', 'ImageInstanceTag', ['ImageInstanceID'], unique=False)
    op.create_index('fk_ImageInstanceTag_Tag1_idx', 'ImageInstanceTag', ['TagID'], unique=False)
    op.create_index('ix_ImageInstanceTag_Image_Tag', 'ImageInstanceTag', ['ImageInstanceID', 'TagID'], unique=False)
    op.create_table('ImageStorage',
    sa.Column('ImageStorageID', sa.Integer(), nullable=False),
    sa.Column('ImageInstanceID', sa.Integer(), nullable=False),
    sa.Column('StorageBackendID', sa.Integer(), nullable=False),
    sa.Column('ObjectKey', sa.String(length=256), nullable=False),
    sa.Column('Hash', sa.BINARY(length=32), nullable=True),
    sa.Column('Checksum', sa.String(length=128), nullable=True),
    sa.Column('Format', sa.String(length=256), nullable=False),
    sa.Column('IsPrimary', sa.Boolean(), nullable=False),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('DateModified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ImageInstanceID'], ['ImageInstance.ImageInstanceID'], ),
    sa.ForeignKeyConstraint(['StorageBackendID'], ['StorageBackend.StorageBackendID'], ),
    sa.PrimaryKeyConstraint('ImageStorageID')
    )
    op.create_index('ObjectKey_StorageBackendID_UNIQUE', 'ImageStorage', ['ObjectKey', 'StorageBackendID'], unique=True)
    op.create_index('ix_ImageStorage_ImageInstanceID_IsPrimary', 'ImageStorage', ['ImageInstanceID', 'IsPrimary'], unique=False)
    op.create_table('ModelSegmentation',
    sa.Column('ModelSegmentationID', sa.Integer(), nullable=False),
    sa.Column('ModelID', sa.Integer(), nullable=False),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ZarrArrayIndex', sa.Integer(), nullable=True),
    sa.Column('ImageInstanceID', sa.Integer(), nullable=False),
    sa.Column('DataRepresentation', sa.Enum('Binary', 'DualBitMask', 'Probability', 'MultiLabel', 'MultiClass', name='datarepresentation'), nullable=False),
    sa.Column('Depth', sa.Integer(), nullable=False),
    sa.Column('Height', sa.Integer(), nullable=False),
    sa.Column('Width', sa.Integer(), nullable=False),
    sa.Column('SparseAxis', sa.Integer(), nullable=True),
    sa.Column('ImageProjectionMatrix', sa.JSON(), nullable=True),
    sa.Column('ScanIndices', sa.JSON(), nullable=True),
    sa.Column('DataType', sa.Enum('R8', 'R8UI', 'R16UI', 'R32UI', 'R32F', name='datatype'), nullable=False),
    sa.Column('Threshold', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ImageInstanceID'], ['ImageInstance.ImageInstanceID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ModelID'], ['Model.ModelID'], ),
    sa.PrimaryKeyConstraint('ModelSegmentationID')
    )
    op.create_index('ix_ModelSegmentation_Image_Model', 'ModelSegmentation', ['ImageInstanceID', 'ModelID'], unique=False)
    op.create_index('ix_ModelSegmentation_Model_Image', 'ModelSegmentation', ['ModelID', 'ImageInstanceID'], unique=False)
    op.create_table('Segmentation',
    sa.Column('SegmentationID', sa.Integer(), nullable=False),
    sa.Column('CreatorID', sa.Integer(), nullable=False),
    sa.Column('FeatureID', sa.Integer(), nullable=False),
    sa.Column('SubTaskID', sa.Integer(), nullable=True),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('DateModified', sa.DateTime(), nullable=True),
    sa.Column('ReferenceSegmentationID', sa.Integer(), nullable=True),
    sa.Column('Inactive', sa.Boolean(), nullable=False),
    sa.Column('ZarrArrayIndex', sa.Integer(), nullable=True),
    sa.Column('ImageInstanceID', sa.Integer(), nullable=False),
    sa.Column('DataRepresentation', sa.Enum('Binary', 'DualBitMask', 'Probability', 'MultiLabel', 'MultiClass', name='datarepresentation'), nullable=False),
    sa.Column('Depth', sa.Integer(), nullable=False),
    sa.Column('Height', sa.Integer(), nullable=False),
    sa.Column('Width', sa.Integer(), nullable=False),
    sa.Column('SparseAxis', sa.Integer(), nullable=True),
    sa.Column('ImageProjectionMatrix', sa.JSON(), nullable=True),
    sa.Column('ScanIndices', sa.JSON(), nullable=True),
    sa.Column('DataType', sa.Enum('R8', 'R8UI', 'R16UI', 'R32UI', 'R32F', name='datatype'), nullable=False),
    sa.Column('Threshold', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['CreatorID'], ['Creator.CreatorID'], ),
    sa.ForeignKeyConstraint(['FeatureID'], ['Feature.FeatureID'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ImageInstanceID'], ['ImageInstance.ImageInstanceID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ReferenceSegmentationID'], ['Segmentation.SegmentationID'], ),
    sa.ForeignKeyConstraint(['SubTaskID'], ['SubTask.SubTaskID'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('SegmentationID')
    )
    op.create_index('ix_Segmentation_Feature_Inactive', 'Segmentation', ['FeatureID', 'Inactive'], unique=False)
    op.create_index('ix_Segmentation_Image_Feature_Inactive', 'Segmentation', ['ImageInstanceID', 'FeatureID', 'Inactive'], unique=False)
    op.create_index('ix_Segmentation_SubTask_Feature', 'Segmentation', ['SubTaskID', 'FeatureID'], unique=False)
    op.create_table('SubTaskImageLink',
    sa.Column('SubTaskID', sa.Integer(), nullable=False),
    sa.Column('ImageInstanceID', sa.Integer(), nullable=False),
    sa.Column('ImageIndex', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ImageInstanceID'], ['ImageInstance.ImageInstanceID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['SubTaskID'], ['SubTask.SubTaskID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SubTaskID', 'ImageInstanceID'),
    sa.UniqueConstraint('SubTaskID', 'ImageIndex', name='uq_SubTaskImageLink_SubTask_ImageIndex')
    )
    op.create_index('fk_SubTaskImageLink_ImageInstance1_idx', 'SubTaskImageLink', ['ImageInstanceID'], unique=False)
    op.create_index('fk_SubTaskImageLink_SubTask1_idx', 'SubTaskImageLink', ['SubTaskID'], unique=False)
    op.create_index('ix_SubTaskImageLink_Image_SubTask', 'SubTaskImageLink', ['ImageInstanceID', 'SubTaskID'], unique=False)
    op.create_table('AnnotationData',
    sa.Column('AnnotationID', sa.Integer(), nullable=False),
    sa.Column('ScanNr', sa.Integer(), nullable=False),
    sa.Column('ValueInt', sa.Integer(), nullable=True),
    sa.Column('ValueFloat', sa.Float(), nullable=True),
    sa.Column('ValueBlob', mysql.LONGBLOB(), nullable=True),
    sa.Column('DatasetIdentifier', sa.String(length=45), nullable=False),
    sa.Column('DateModified', sa.DateTime(), nullable=True),
    sa.Column('MediaType', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['AnnotationID'], ['Annotation.AnnotationID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('AnnotationID', 'ScanNr'),
    sa.UniqueConstraint('DatasetIdentifier')
    )
    op.create_index('fk_AnnotationData_Annotation1_idx', 'AnnotationData', ['AnnotationID'], unique=False)
    op.create_table('AnnotationTag',
    sa.Column('TagID', sa.Integer(), nullable=False),
    sa.Column('AnnotationID', sa.Integer(), nullable=False),
    sa.Column('CreatorID', sa.Integer(), nullable=False),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['AnnotationID'], ['Annotation.AnnotationID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['CreatorID'], ['Creator.CreatorID'], ),
    sa.ForeignKeyConstraint(['TagID'], ['Tag.TagID'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('TagID', 'AnnotationID')
    )
    op.create_index('fk_AnnotationTag_Annotation1_idx', 'AnnotationTag', ['AnnotationID'], unique=False)
    op.create_index('fk_AnnotationTag_Creator1_idx', 'AnnotationTag', ['CreatorID'], unique=False)
    op.create_index('fk_AnnotationTag_Tag1_idx', 'AnnotationTag', ['TagID'], unique=False)
    op.create_index('ix_AnnotationTag_Annotation_Tag', 'AnnotationTag', ['AnnotationID', 'TagID'], unique=False)
    op.create_table('AttributeValue',
    sa.Column('AttributeValueID', sa.Integer(), nullable=False),
    sa.Column('AttributeID', sa.Integer(), nullable=False),
    sa.Column('ModelID', sa.Integer(), nullable=True),
    sa.Column('ImageInstanceID', sa.Integer(), nullable=True),
    sa.Column('SegmentationID', sa.Integer(), nullable=True),
    sa.Column('ModelSegmentationID', sa.Integer(), nullable=True),
    sa.Column('PatientID', sa.Integer(), nullable=True),
    sa.Column('StudyID', sa.Integer(), nullable=True),
    sa.Column('Laterality', sa.Enum('L', 'R', name='laterality'), nullable=True),
    sa.Column('ValueFloat', sa.Float(), nullable=True),
    sa.Column('ValueInt', sa.Integer(), nullable=True),
    sa.Column('ValueText', sa.String(length=255), nullable=True),
    sa.Column('ValueJSON', sa.JSON(), nullable=True),
    sa.CheckConstraint('(ImageInstanceID IS NOT NULL AND SegmentationID IS NULL AND ModelSegmentationID IS NULL AND PatientID IS NULL AND StudyID IS NULL) OR (ImageInstanceID IS NULL AND SegmentationID IS NOT NULL AND ModelSegmentationID IS NULL AND PatientID IS NULL AND StudyID IS NULL) OR (ImageInstanceID IS NULL AND SegmentationID IS NULL AND ModelSegmentationID IS NOT NULL AND PatientID IS NULL AND StudyID IS NULL) OR (ImageInstanceID IS NULL AND SegmentationID IS NULL AND ModelSegmentationID IS NULL AND PatientID IS NOT NULL AND StudyID IS NULL) OR (ImageInstanceID IS NULL AND SegmentationID IS NULL AND ModelSegmentationID IS NULL AND PatientID IS NULL AND StudyID IS NOT NULL)', name='ck_AttributeValue_exactly_one_entity'),
    sa.ForeignKeyConstraint(['AttributeID'], ['AttributeDefinition.AttributeID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ImageInstanceID'], ['ImageInstance.ImageInstanceID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ModelID'], ['Model.ModelID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ModelSegmentationID'], ['ModelSegmentation.ModelSegmentationID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['PatientID'], ['Patient.PatientID'], ),
    sa.ForeignKeyConstraint(['SegmentationID'], ['Segmentation.SegmentationID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['StudyID'], ['Study.StudyID'], ),
    sa.PrimaryKeyConstraint('AttributeValueID'),
    sa.UniqueConstraint('ImageInstanceID', 'AttributeID', 'ModelID', name='uq_AttributeValue_image_attribute_model'),
    sa.UniqueConstraint('ModelSegmentationID', 'AttributeID', 'ModelID', name='uq_AttributeValue_modelseg_attribute_model'),
    sa.UniqueConstraint('PatientID', 'AttributeID', 'ModelID', name='uq_AttributeValue_patient_attribute_model'),
    sa.UniqueConstraint('SegmentationID', 'AttributeID', 'ModelID', name='uq_AttributeValue_segmentation_attribute_model'),
    sa.UniqueConstraint('StudyID', 'AttributeID', 'ModelID', name='uq_AttributeValue_study_attribute_model')
    )
    op.create_index('fk_AttributeValue_Attribute1_idx', 'AttributeValue', ['AttributeID'], unique=False)
    op.create_index('fk_AttributeValue_ImageInstance1_idx', 'AttributeValue', ['ImageInstanceID'], unique=False)
    op.create_index('fk_AttributeValue_Model1_idx', 'AttributeValue', ['ModelID'], unique=False)
    op.create_index('fk_AttributeValue_ModelSegmentation1_idx', 'AttributeValue', ['ModelSegmentationID'], unique=False)
    op.create_index('fk_AttributeValue_Patient1_idx', 'AttributeValue', ['PatientID'], unique=False)
    op.create_index('fk_AttributeValue_Segmentation1_idx', 'AttributeValue', ['SegmentationID'], unique=False)
    op.create_index('fk_AttributeValue_Study1_idx', 'AttributeValue', ['StudyID'], unique=False)
    op.create_index('ix_AttributeValue_ImageInstance_Attribute', 'AttributeValue', ['ImageInstanceID', 'AttributeID'], unique=False)
    op.create_index('ix_AttributeValue_ModelSegmentation_Attribute', 'AttributeValue', ['ModelSegmentationID', 'AttributeID'], unique=False)
    op.create_index('ix_AttributeValue_Patient_Attribute', 'AttributeValue', ['PatientID', 'AttributeID'], unique=False)
    op.create_index('ix_AttributeValue_Segmentation_Attribute', 'AttributeValue', ['SegmentationID', 'AttributeID'], unique=False)
    op.create_index('ix_AttributeValue_Study_Attribute', 'AttributeValue', ['StudyID', 'AttributeID'], unique=False)
    op.create_table('FormAnnotationTag',
    sa.Column('TagID', sa.Integer(), nullable=False),
    sa.Column('FormAnnotationID', sa.Integer(), nullable=False),
    sa.Column('CreatorID', sa.Integer(), nullable=False),
    sa.Column('Comment', sa.String(length=256), nullable=True),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['CreatorID'], ['Creator.CreatorID'], ),
    sa.ForeignKeyConstraint(['FormAnnotationID'], ['FormAnnotation.FormAnnotationID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['TagID'], ['Tag.TagID'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('TagID', 'FormAnnotationID')
    )
    op.create_index('fk_FormAnnotationTag_Creator1_idx', 'FormAnnotationTag', ['CreatorID'], unique=False)
    op.create_index('fk_FormAnnotationTag_FormAnnotation1_idx', 'FormAnnotationTag', ['FormAnnotationID'], unique=False)
    op.create_index('fk_FormAnnotationTag_Tag1_idx', 'FormAnnotationTag', ['TagID'], unique=False)
    op.create_index('ix_FormAnnotationTag_Form_Tag', 'FormAnnotationTag', ['FormAnnotationID', 'TagID'], unique=False)
    op.create_table('SegmentationTag',
    sa.Column('TagID', sa.Integer(), nullable=False),
    sa.Column('SegmentationID', sa.Integer(), nullable=False),
    sa.Column('CreatorID', sa.Integer(), nullable=False),
    sa.Column('Comment', sa.String(length=256), nullable=True),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['CreatorID'], ['Creator.CreatorID'], ),
    sa.ForeignKeyConstraint(['SegmentationID'], ['Segmentation.SegmentationID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['TagID'], ['Tag.TagID'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('TagID', 'SegmentationID')
    )
    op.create_index('fk_SegmentationTag_Creator1_idx', 'SegmentationTag', ['CreatorID'], unique=False)
    op.create_index('fk_SegmentationTag_Segmentation1_idx', 'SegmentationTag', ['SegmentationID'], unique=False)
    op.create_index('fk_SegmentationTag_Tag1_idx', 'SegmentationTag', ['TagID'], unique=False)
    op.create_index('ix_SegmentationTag_Segmentation_Tag', 'SegmentationTag', ['SegmentationID', 'TagID'], unique=False)
    op.create_table('AttributeValueInput',
    sa.Column('OutputAttributeValueID', sa.Integer(), nullable=False),
    sa.Column('InputAttributeValueID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['InputAttributeValueID'], ['AttributeValue.AttributeValueID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['OutputAttributeValueID'], ['AttributeValue.AttributeValueID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('OutputAttributeValueID', 'InputAttributeValueID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Refuse to downgrade: the inverse of this root revision drops all 44 tables,
    and deployed databases are stamped at it without ``upgrade()`` ever running.
    """
    raise NotImplementedError(
        "orm_baseline is the root revision; downgrading it would drop the entire schema."
    )
