"""new indices

Revision ID: 335c6bcc1fd8
Revises: 13a6246c9119
Create Date: 2025-11-25 13:38:16.724642

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "335c6bcc1fd8"
down_revision: Union[str, None] = "13a6246c9119"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_AnnotationTag_Annotation_Tag",
        "AnnotationTag",
        ["AnnotationID", "TagID"],
        unique=False,
    )
    op.create_index(
        "ix_AttributeValue_ImageInstance_Attribute",
        "AttributeValue",
        ["ImageInstanceID", "AttributeID"],
        unique=False,
    )
    op.create_index(
        "ix_AttributeValue_ModelSegmentation_Attribute",
        "AttributeValue",
        ["ModelSegmentationID", "AttributeID"],
        unique=False,
    )
    op.create_index(
        "ix_AttributeValue_Patient_Attribute",
        "AttributeValue",
        ["PatientID", "AttributeID"],
        unique=False,
    )
    op.create_index(
        "ix_AttributeValue_Segmentation_Attribute",
        "AttributeValue",
        ["SegmentationID", "AttributeID"],
        unique=False,
    )
    op.create_index(
        "ix_AttributeValue_Study_Attribute",
        "AttributeValue",
        ["StudyID", "AttributeID"],
        unique=False,
    )
    op.create_index(
        "ix_FormAnnotation_FormSchema_Inactive_Creator",
        "FormAnnotation",
        ["FormSchemaID", "Inactive", "CreatorID"],
        unique=False,
    )
    op.create_index(
        "ix_FormAnnotation_Image_Laterality_Inactive",
        "FormAnnotation",
        ["ImageInstanceID", "Laterality", "Inactive"],
        unique=False,
    )
    op.create_index(
        "ix_FormAnnotation_Patient_Study_Inactive",
        "FormAnnotation",
        ["PatientID", "StudyID", "Inactive"],
        unique=False,
    )
    op.create_index(
        "ix_FormAnnotation_SubTask_Inactive",
        "FormAnnotation",
        ["SubTaskID", "Inactive"],
        unique=False,
    )
    op.create_index(
        "ix_FormAnnotationTag_Form_Tag",
        "FormAnnotationTag",
        ["FormAnnotationID", "TagID"],
        unique=False,
    )
    op.create_index(
        "fk_ImageInstance_Series_Inactive1_idx",
        "ImageInstance",
        ["SeriesID", "Inactive"],
        unique=False,
    )
    op.create_index(
        "ix_ImageInstance_Modality_Inactive_ETDRSField",
        "ImageInstance",
        ["Modality", "Inactive", "ETDRSField"],
        unique=False,
    )
    op.create_index(
        "ix_ImageInstance_Modality_Inactive_Laterality",
        "ImageInstance",
        ["Modality", "Inactive", "Laterality"],
        unique=False,
    )
    op.create_index(
        "ix_ImageInstanceTag_Image_Tag",
        "ImageInstanceTag",
        ["ImageInstanceID", "TagID"],
        unique=False,
    )
    op.create_index(
        "ix_ModelSegmentation_Image_Model",
        "ModelSegmentation",
        ["ImageInstanceID", "ModelID"],
        unique=False,
    )
    op.create_index(
        "ix_ModelSegmentation_Model_Image",
        "ModelSegmentation",
        ["ModelID", "ImageInstanceID"],
        unique=False,
    )
    op.drop_index("ProjectIDPatientIdentifier_UNIQUE", table_name="Patient")
    op.create_index(
        "ProjectIDPatientIdentifier_UNIQUE",
        "Patient",
        ["ProjectID", "PatientIdentifier"],
        unique=True,
    )
    op.create_index(
        "ix_Patient_Project_Sex_BirthDate",
        "Patient",
        ["ProjectID", "Sex", "BirthDate"],
        unique=False,
    )
    op.create_index(
        "ix_Segmentation_Feature_Inactive",
        "Segmentation",
        ["FeatureID", "Inactive"],
        unique=False,
    )
    op.create_index(
        "ix_Segmentation_Image_Feature_Inactive",
        "Segmentation",
        ["ImageInstanceID", "FeatureID", "Inactive"],
        unique=False,
    )
    op.create_index(
        "ix_Segmentation_SubTask_Feature",
        "Segmentation",
        ["SubTaskID", "FeatureID"],
        unique=False,
    )
    op.create_index(
        "ix_SegmentationTag_Segmentation_Tag",
        "SegmentationTag",
        ["SegmentationID", "TagID"],
        unique=False,
    )
    op.create_index(
        "ix_Series_StudyID_SeriesNumber",
        "Series",
        ["StudyID", "SeriesNumber"],
        unique=False,
    )
    op.create_index(
        "ix_Series_StudyID_StudyInstanceUid",
        "Series",
        ["StudyID", "StudyInstanceUid"],
        unique=False,
    )
    op.drop_index("PatientIDStudyDate_UNIQUE", table_name="Study")
    op.create_index(
        "PatientIDStudyDate_UNIQUE", "Study", ["PatientID", "StudyDate"], unique=True
    )
    op.create_index(
        "ix_Study_PatientID_StudyRound",
        "Study",
        ["PatientID", "StudyRound"],
        unique=False,
    )
    op.create_index(
        "ix_Study_StudyRound_StudyDate",
        "Study",
        ["StudyRound", "StudyDate"],
        unique=False,
    )
    op.create_index(
        "ix_StudyTag_Study_Tag", "StudyTag", ["StudyID", "TagID"], unique=False
    )
    op.create_index(
        "ix_SubTask_TaskState_Creator",
        "SubTask",
        ["TaskState", "CreatorID"],
        unique=False,
    )
    op.create_index(
        "ix_SubTaskImageLink_Image_SubTask",
        "SubTaskImageLink",
        ["ImageInstanceID", "SubTaskID"],
        unique=False,
    )
    op.create_index(
        "ix_Task_Creator_TaskDefinition",
        "Task",
        ["CreatorID", "TaskDefinitionID"],
        unique=False,
    )
    # ### end Alembic commands ###
