"""add laterality to FormAnnotation

Revision ID: c5744885fe94
Revises: eac6e6f7dcea
Create Date: 2025-11-04 17:17:40.159997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5744885fe94'
down_revision: Union[str, None] = 'eac6e6f7dcea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FormAnnotation', sa.Column('Laterality', sa.Enum('L', 'R', name='laterality'), nullable=True))
    op.add_column('FormSchema', sa.Column('EntityType', sa.Enum('Patient', 'Study', 'Eye', 'StudyEye', 'ImageInstance', name='entitytype'), nullable=True))
    
    # Populate Laterality from ImageInstance for existing entries
    op.execute(
        """
        UPDATE FormAnnotation AS fa
        JOIN ImageInstance AS ii ON fa.ImageInstanceID = ii.ImageInstanceID
        SET fa.Laterality = ii.Laterality
        WHERE fa.ImageInstanceID IS NOT NULL
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FormSchema', 'EntityType')
    op.drop_column('FormAnnotation', 'Laterality')
    # ### end Alembic commands ###
