"""task creator and state

Revision ID: 62b55e9c9e70
Revises: 31212c7f33fd
Create Date: 2025-09-22 11:43:18.044096
 
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '62b55e9c9e70'
down_revision: Union[str, None] = '31212c7f33fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, drop the foreign key constraint
    op.drop_constraint('FormAnnotation_ibfk_3', 'FormAnnotation', type_='foreignkey')
    
    # Drop the old index (if it still exists after FK drop)
    op.drop_index('fk_FormAnnotation_FormAnnotation1', table_name='FormAnnotation')
    
    # Create the new index with proper naming convention
    op.create_index(op.f('ix_FormAnnotation_FormAnnotationReferenceID'), 'FormAnnotation', ['FormAnnotationReferenceID'], unique=False)
    
    # Recreate the foreign key constraint
    op.create_foreign_key(
        'fk_FormAnnotation_FormAnnotationReferenceID',
        'FormAnnotation', 'FormAnnotation',
        ['FormAnnotationReferenceID'], ['FormAnnotationID'],
        ondelete='CASCADE'
    )

    op.create_foreign_key(None, 'FormAnnotation', 'SubTask', ['SubTaskID'], ['SubTaskID'], ondelete='SET NULL')


    op.add_column('Task', sa.Column('CreatorID', sa.Integer(), nullable=True))
    op.add_column('Task', sa.Column('TaskState', sa.Enum('NotStarted', 'Busy', 'Finished', 'Aborted', 'Archived', name='taskstate'), nullable=False))
    op.create_foreign_key(None, 'Task', 'Creator', ['CreatorID'], ['CreatorID'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(None, 'Task', type_='foreignkey')
    op.drop_column('Task', 'TaskState')
    op.drop_column('Task', 'CreatorID')

    op.drop_constraint(None, 'FormAnnotation', type_='foreignkey')

    # Drop the foreign key
    op.drop_constraint('fk_FormAnnotation_FormAnnotationReferenceID', 'FormAnnotation', type_='foreignkey')
    
    # Drop the new index
    op.drop_index(op.f('ix_FormAnnotation_FormAnnotationReferenceID'), table_name='FormAnnotation')
    
    # Recreate the old index
    op.create_index('fk_FormAnnotation_FormAnnotation1', 'FormAnnotation', ['FormAnnotationReferenceID'], unique=False)
    
    # Recreate the original foreign key
    op.create_foreign_key(
        'FormAnnotation_ibfk_3',
        'FormAnnotation', 'FormAnnotation',
        ['FormAnnotationReferenceID'], ['FormAnnotationID'],
        ondelete='CASCADE'
    )

    