"""move-studyInstanceUid

Revision ID: eac6e6f7dcea
Revises: ccb5ba8245c7
Create Date: 2025-10-24 15:04:51.008989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eac6e6f7dcea'
down_revision: Union[str, None] = 'ccb5ba8245c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ImageInstance', sa.Column('AltDatasetIdentifier', sa.String(length=256), nullable=True))
    op.alter_column('ImageInstance', 'Laterality',
               existing_type=mysql.ENUM('L', 'R'),
               nullable=False)
    op.add_column('Series', sa.Column('StudyInstanceUid', sa.String(length=64), nullable=True))
    
    # Migrate existing StudyInstanceUid values from Study to Series
    op.execute(
        """
        UPDATE `Series` AS s
        JOIN `Study` AS st ON s.StudyID = st.StudyID
        SET s.StudyInstanceUid = st.StudyInstanceUid
        WHERE st.StudyInstanceUid IS NOT NULL
        """
    )
    
    op.create_index('StudyInstanceUidSeriesInstanceUid_UNIQUE', 'Series', ['StudyInstanceUid', 'SeriesInstanceUid'], unique=True)
    op.drop_index('StudyInstanceUid_UNIQUE', table_name='Study')
    op.drop_column('Study', 'StudyInstanceUid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Study', sa.Column('StudyInstanceUid', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('StudyInstanceUid_UNIQUE', 'Study', ['StudyInstanceUid'], unique=True)
    op.drop_index('StudyInstanceUidSeriesInstanceUid_UNIQUE', table_name='Series')
    op.drop_column('Series', 'StudyInstanceUid')
    op.alter_column('ImageInstance', 'Laterality',
               existing_type=mysql.ENUM('L', 'R'),
               nullable=True)
    op.drop_column('ImageInstance', 'AltDatasetIdentifier')
    # ### end Alembic commands ###
