"""advanced attributes model

Revision ID: 048a18ac8486
Revises: 496f91a008b7
Create Date: 2025-10-23 10:39:22.953270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '048a18ac8486'
down_revision: Union[str, None] = '496f91a008b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AttributeDefinition',
    sa.Column('AttributeID', sa.Integer(), nullable=False),
    sa.Column('AttributeName', sa.String(length=255), nullable=False),
    sa.Column('AttributeDataType', sa.Enum('String', 'Float', 'Int', 'JSON', name='attributedatatype'), nullable=False),
    sa.PrimaryKeyConstraint('AttributeID'),
    sa.UniqueConstraint('AttributeName', name='uq_AttributeDefinition_AttributeName')
    )
    op.create_table('AttributesModelOutput',
    sa.Column('ModelID', sa.Integer(), nullable=False),
    sa.Column('AttributeID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['AttributeID'], ['AttributeDefinition.AttributeID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ModelID'], ['AttributesModel.ModelID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ModelID', 'AttributeID')
    )
    op.create_table('ModelInput',
    sa.Column('ModelInputID', sa.Integer(), nullable=False),
    sa.Column('ModelID', sa.Integer(), nullable=False),
    sa.Column('InputAttributeID', sa.Integer(), nullable=False),
    sa.Column('InputName', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['InputAttributeID'], ['AttributeDefinition.AttributeID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ModelID'], ['AttributesModel.ModelID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ModelInputID'),
    sa.UniqueConstraint('ModelID', 'InputAttributeID', name='uq_ModelInput_ModelID_InputAttributeID')
    )
    op.create_index('fk_ModelInput_Attribute1_idx', 'ModelInput', ['InputAttributeID'], unique=False)
    op.create_index('fk_ModelInput_Model1_idx', 'ModelInput', ['ModelID'], unique=False)
    op.create_table('AttributeValue',
    sa.Column('AttributeValueID', sa.Integer(), nullable=False),
    sa.Column('AttributeID', sa.Integer(), nullable=False),
    sa.Column('ModelID', sa.Integer(), nullable=False),
    sa.Column('ImageInstanceID', sa.Integer(), nullable=True),
    sa.Column('SegmentationID', sa.Integer(), nullable=True),
    sa.Column('ModelSegmentationID', sa.Integer(), nullable=True),
    sa.Column('ValueFloat', sa.Float(), nullable=True),
    sa.Column('ValueInt', sa.Integer(), nullable=True),
    sa.Column('ValueText', sa.String(length=255), nullable=True),
    sa.Column('ValueJSON', sa.JSON(), nullable=True),
    sa.CheckConstraint('(ImageInstanceID IS NOT NULL AND SegmentationID IS NULL AND ModelSegmentationID IS NULL) OR (ImageInstanceID IS NULL AND SegmentationID IS NOT NULL AND ModelSegmentationID IS NULL) OR (ImageInstanceID IS NULL AND SegmentationID IS NULL AND ModelSegmentationID IS NOT NULL)', name='ck_AttributeValue_exactly_one_entity'),
    sa.ForeignKeyConstraint(['AttributeID'], ['AttributeDefinition.AttributeID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ImageInstanceID'], ['ImageInstance.ImageInstanceID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ModelID'], ['Model.ModelID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ModelSegmentationID'], ['ModelSegmentation.ModelSegmentationID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['SegmentationID'], ['Segmentation.SegmentationID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('AttributeValueID'),
    )
    op.create_unique_constraint('uq_AttributeValue_image_attribute_model', 'AttributeValue', ['ImageInstanceID', 'AttributeID', 'ModelID'])
    op.create_unique_constraint('uq_AttributeValue_modelseg_attribute_model', 'AttributeValue', ['ModelSegmentationID', 'AttributeID', 'ModelID'])
    op.create_unique_constraint('uq_AttributeValue_segmentation_attribute_model', 'AttributeValue', ['SegmentationID', 'AttributeID', 'ModelID'])
   
    
    op.create_index('fk_AttributeValue_Attribute1_idx', 'AttributeValue', ['AttributeID'], unique=False)
    op.create_index('fk_AttributeValue_ImageInstance1_idx', 'AttributeValue', ['ImageInstanceID'], unique=False)
    op.create_index('fk_AttributeValue_Model1_idx', 'AttributeValue', ['ModelID'], unique=False)
    op.create_index('fk_AttributeValue_ModelSegmentation1_idx', 'AttributeValue', ['ModelSegmentationID'], unique=False)
    op.create_index('fk_AttributeValue_Segmentation1_idx', 'AttributeValue', ['SegmentationID'], unique=False)
    op.create_table('AttributeValueInput',
    sa.Column('OutputAttributeValueID', sa.Integer(), nullable=False),
    sa.Column('InputAttributeValueID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['InputAttributeValueID'], ['AttributeValue.AttributeValueID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['OutputAttributeValueID'], ['AttributeValue.AttributeValueID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('OutputAttributeValueID', 'InputAttributeValueID')
    )
    
    # op.drop_index('fk_ImageAttributes_Attribute1_idx', table_name='ImageAttributes')
    # op.drop_index('fk_ImageAttributes_ImageInstance1_idx', table_name='ImageAttributes')
    # op.drop_index('uq_ImageAttributes_ImageInstanceID_AttributeID', table_name='ImageAttributes')
    op.drop_table('ImageAttributes')
    # op.drop_index('fk_Attributes_Model1_idx', table_name='Attributes')
    # op.drop_index('uq_Attributes_ModelID_AttributeName', table_name='Attributes')
    op.drop_table('Attributes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Attributes',
    sa.Column('AttributeID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('AttributeName', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('AttributeDataType', mysql.ENUM('String', 'Float', 'Int', 'JSON'), nullable=False),
    sa.Column('ModelID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ModelID'], ['Model.ModelID'], name='Attributes_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('AttributeID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_Attributes_ModelID_AttributeName', 'Attributes', ['ModelID', 'AttributeName'], unique=True)
    op.create_index('fk_Attributes_Model1_idx', 'Attributes', ['ModelID'], unique=False)
    op.create_table('ImageAttributes',
    sa.Column('ImageAttributeID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ImageInstanceID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('AttributeID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ValueFloat', mysql.FLOAT(), nullable=True),
    sa.Column('ValueInt', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ValueText', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ValueJSON', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['AttributeID'], ['Attributes.AttributeID'], name='ImageAttributes_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ImageInstanceID'], ['ImageInstance.ImageInstanceID'], name='ImageAttributes_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ImageAttributeID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_ImageAttributes_ImageInstanceID_AttributeID', 'ImageAttributes', ['ImageInstanceID', 'AttributeID'], unique=True)
    op.create_index('fk_ImageAttributes_ImageInstance1_idx', 'ImageAttributes', ['ImageInstanceID'], unique=False)
    op.create_index('fk_ImageAttributes_Attribute1_idx', 'ImageAttributes', ['AttributeID'], unique=False)
    op.drop_table('AttributeValueInput')
    op.drop_index('fk_AttributeValue_Segmentation1_idx', table_name='AttributeValue')
    op.drop_index('fk_AttributeValue_ModelSegmentation1_idx', table_name='AttributeValue')
    op.drop_index('fk_AttributeValue_Model1_idx', table_name='AttributeValue')
    op.drop_index('fk_AttributeValue_ImageInstance1_idx', table_name='AttributeValue')
    op.drop_index('fk_AttributeValue_Attribute1_idx', table_name='AttributeValue')
    op.drop_table('AttributeValue')
    op.drop_index('fk_ModelInput_Model1_idx', table_name='ModelInput')
    op.drop_index('fk_ModelInput_Attribute1_idx', table_name='ModelInput')
    op.drop_table('ModelInput')
    op.drop_table('AttributesModelOutput')
    op.drop_table('AttributeDefinition')
    # ### end Alembic commands ###
