"""tagging comments

Revision ID: 65eaddf0f0f8
Revises: c5744885fe94
Create Date: 2025-11-07 16:28:11.470733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '65eaddf0f0f8'
down_revision: Union[str, None] = 'c5744885fe94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_FormAnnotation_FormAnnotationReferenceID'), 'FormAnnotation', ['FormAnnotationReferenceID'], unique=False)
    op.add_column('FormAnnotationTag', sa.Column('Comment', sa.String(length=256), nullable=True))
    op.alter_column('ImageInstance', 'Inactive',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.add_column('ImageInstanceTag', sa.Column('Comment', sa.String(length=256), nullable=True))
    op.add_column('SegmentationTag', sa.Column('Comment', sa.String(length=256), nullable=True))
    op.add_column('StudyTag', sa.Column('Comment', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('StudyTag', 'Comment')
    op.drop_column('SegmentationTag', 'Comment')
    op.drop_column('ImageInstanceTag', 'Comment')
    op.alter_column('ImageInstance', 'Inactive',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_column('FormAnnotationTag', 'Comment')
    op.drop_index(op.f('ix_FormAnnotation_FormAnnotationReferenceID'), table_name='FormAnnotation')
    # ### end Alembic commands ###
