"""New api

Revision ID: b5d7958b7e13
Revises: e69c5e4002ed
Create Date: 2025-09-10 10:41:52.425566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d7958b7e13'
down_revision: Union[str, None] = 'e69c5e4002ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('CreatorTag',
    sa.Column('TagID', sa.Integer(), nullable=False),
    sa.Column('CreatorID', sa.Integer(), nullable=False),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['CreatorID'], ['Creator.CreatorID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['TagID'], ['Tag.TagID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('TagID', 'CreatorID')
    )
    op.create_index('fk_CreatorTag_Creator1_idx', 'CreatorTag', ['CreatorID'], unique=False)
    op.create_index('fk_CreatorTag_Tag1_idx', 'CreatorTag', ['TagID'], unique=False)


    op.create_table('AnnotationTag',
    sa.Column('TagID', sa.Integer(), nullable=False),
    sa.Column('AnnotationID', sa.Integer(), nullable=False),
    sa.Column('CreatorID', sa.Integer(), nullable=False),
    sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['AnnotationID'], ['Annotation.AnnotationID'], ),
    sa.ForeignKeyConstraint(['CreatorID'], ['Creator.CreatorID'], ),
    sa.ForeignKeyConstraint(['TagID'], ['Tag.TagID'], ),
    sa.PrimaryKeyConstraint('TagID', 'AnnotationID')
    )
    op.create_index('fk_AnnotationTag_Annotation1_idx', 'AnnotationTag', ['AnnotationID'], unique=False)
    op.create_index('fk_AnnotationTag_Creator1_idx', 'AnnotationTag', ['CreatorID'], unique=False)
    op.create_index('fk_AnnotationTag_Tag1_idx', 'AnnotationTag', ['TagID'], unique=False)
    op.create_foreign_key(None, 'Annotation', 'Annotation', ['AnnotationReferenceID'], ['AnnotationID'])
    op.add_column('FormAnnotationTag', sa.Column('CreatorID', sa.Integer(), nullable=False))
    op.add_column('FormAnnotationTag', sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index('fk_FormAnnotationTag_Creator1_idx', 'FormAnnotationTag', ['CreatorID'], unique=False)
    op.create_foreign_key(None, 'FormAnnotationTag', 'Creator', ['CreatorID'], ['CreatorID'])
    op.add_column('ImageInstanceTag', sa.Column('CreatorID', sa.Integer(), nullable=False))
    op.add_column('ImageInstanceTag', sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index('fk_ImageInstanceTag_Creator1_idx', 'ImageInstanceTag', ['CreatorID'], unique=False)
    op.create_foreign_key(None, 'ImageInstanceTag', 'Creator', ['CreatorID'], ['CreatorID'])
    op.create_index('fk_Project_Contact1_idx', 'Project', ['ContactID'], unique=False)
    op.add_column('SegmentationTag', sa.Column('CreatorID', sa.Integer(), nullable=False))
    op.add_column('SegmentationTag', sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index('fk_SegmentationTag_Creator1_idx', 'SegmentationTag', ['CreatorID'], unique=False)
    op.create_foreign_key(None, 'SegmentationTag', 'Creator', ['CreatorID'], ['CreatorID'])
    op.add_column('StudyTag', sa.Column('CreatorID', sa.Integer(), nullable=False))
    op.add_column('StudyTag', sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index('fk_StudyTag_Creator1_idx', 'StudyTag', ['CreatorID'], unique=False)
    op.create_foreign_key(None, 'StudyTag', 'Creator', ['CreatorID'], ['CreatorID'])
    op.add_column('Tag', sa.Column('TagType', sa.Enum('Study', 'ImageInstance', 'Annotation', 'Segmentation', 'FormAnnotation', name='tagtype'), nullable=False))
    op.add_column('Tag', sa.Column('TagDescription', sa.String(length=256), nullable=False))
    op.add_column('Tag', sa.Column('CreatorID', sa.Integer(), nullable=False))
    op.add_column('Tag', sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index('fk_Tag_Creator1_idx', 'Tag', ['CreatorID'], unique=False)
    op.create_foreign_key(None, 'Tag', 'Creator', ['CreatorID'], ['CreatorID'])
    # ### end Alembic commands ###

