"""not null AttributeValue.ModelID and ImageInstance.ModalityID

Revision ID: 617b4b980d71
Revises: 10d5ab598dc7
Create Date: 2025-11-23 20:45:29.234457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '617b4b980d71'
down_revision: Union[str, None] = '10d5ab598dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('AttributeValue', 'ModelID',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('ImageInstance', 'ModalityID',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ImageInstance', 'ModalityID',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('AttributeValue', 'ModelID',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
