"""Make tag name unique per type

Revision ID: 60f64f6c2042
Revises: 62b55e9c9e70
Create Date: 2025-10-09 17:32:45.987115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60f64f6c2042'
down_revision: Union[str, None] = '62b55e9c9e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('TagName_UNIQUE', table_name='Tag')
    op.create_unique_constraint('Tag', 'Tag', ['TagName', 'TagType'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Tag', 'Tag', type_='unique')
    op.create_index('TagName_UNIQUE', 'Tag', ['TagName'], unique=True)
    # ### end Alembic commands ###
