"""attributes

Revision ID: 496f91a008b7
Revises: 60f64f6c2042
Create Date: 2025-10-20 19:54:01.469260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '496f91a008b7'
down_revision: Union[str, None] = '60f64f6c2042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # add and populate ModelType column as an enum (segmentation | attributes)
    modelkind_enum = sa.Enum('segmentation', 'attributes', name='modelkind')
    modelkind_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('Model', sa.Column('ModelType', modelkind_enum, nullable=True))
    op.execute(sa.text("UPDATE Model SET ModelType = 'segmentation' WHERE ModelType IS NULL"))
    op.alter_column('Model', 'ModelType', existing_type=modelkind_enum, nullable=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Attributes',
    sa.Column('AttributeID', sa.Integer(), nullable=False),
    sa.Column('AttributeName', sa.String(length=255), nullable=False),
    sa.Column('AttributeDataType', sa.Enum('String', 'Float', 'Int', 'JSON', name='attributedatatype'), nullable=False),
    sa.Column('ModelID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ModelID'], ['Model.ModelID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('AttributeID'),
    sa.UniqueConstraint('ModelID', 'AttributeName', name='uq_Attributes_ModelID_AttributeName')
    )
    op.create_index('fk_Attributes_Model1_idx', 'Attributes', ['ModelID'], unique=False)
    op.create_table('AttributesModel',
    sa.Column('ModelID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ModelID'], ['Model.ModelID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ModelID')
    )
    op.create_table('SegmentationModel',
    sa.Column('ModelID', sa.Integer(), nullable=False),
    sa.Column('FeatureID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['FeatureID'], ['Feature.FeatureID'], ),
    sa.ForeignKeyConstraint(['ModelID'], ['Model.ModelID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ModelID')
    )
    op.create_table('ImageAttributes',
    sa.Column('ImageAttributeID', sa.Integer(), nullable=False),
    sa.Column('ImageInstanceID', sa.Integer(), nullable=False),
    sa.Column('AttributeID', sa.Integer(), nullable=False),
    sa.Column('ValueFloat', sa.Float(), nullable=True),
    sa.Column('ValueInt', sa.Integer(), nullable=True),
    sa.Column('ValueText', sa.String(length=255), nullable=True),
    sa.Column('ValueJSON', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['AttributeID'], ['Attributes.AttributeID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ImageInstanceID'], ['ImageInstance.ImageInstanceID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ImageAttributeID'),
    sa.UniqueConstraint('ImageInstanceID', 'AttributeID', name='uq_ImageAttributes_ImageInstanceID_AttributeID')
    )

    # migrate segmentation models to SegmentationModel table
    op.execute(sa.text("""
        INSERT INTO SegmentationModel (ModelID, FeatureID)
        SELECT ModelID, FeatureID
        FROM Model
    """))

    # drop foreign key from Model to Feature
    op.create_index('fk_ImageAttributes_Attribute1_idx', 'ImageAttributes', ['AttributeID'], unique=False)
    op.create_index('fk_ImageAttributes_ImageInstance1_idx', 'ImageAttributes', ['ImageInstanceID'], unique=False)
    
    op.drop_constraint('Model_ibfk_1', 'Model', type_='foreignkey')
    op.drop_column('Model', 'FeatureID')
    # ### end Alembic commands ###

