"""laterality nullable

Revision ID: 13a6246c9119
Revises: 617b4b980d71
Create Date: 2025-11-23 22:14:47.324671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '13a6246c9119'
down_revision: Union[str, None] = '617b4b980d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ImageInstance', 'Laterality',
               existing_type=mysql.ENUM('L', 'R'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ImageInstance', 'Laterality',
               existing_type=mysql.ENUM('L', 'R'),
               nullable=False)
    # ### end Alembic commands ###
