"""adding columns to attributevalue

Revision ID: 10d5ab598dc7
Revises: 65eaddf0f0f8
Create Date: 2025-11-12 19:45:51.402074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d5ab598dc7'
down_revision: Union[str, None] = '65eaddf0f0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AttributeValue', sa.Column('PatientID', sa.Integer(), nullable=True))
    op.add_column('AttributeValue', sa.Column('StudyID', sa.Integer(), nullable=True))
    op.add_column('AttributeValue', sa.Column('Laterality', sa.Enum('L', 'R', name='laterality'), nullable=True))
    op.create_index('fk_AttributeValue_Patient1_idx', 'AttributeValue', ['PatientID'], unique=False)
    op.create_index('fk_AttributeValue_Study1_idx', 'AttributeValue', ['StudyID'], unique=False)
    op.create_unique_constraint('uq_AttributeValue_patient_attribute_model', 'AttributeValue', ['PatientID', 'AttributeID', 'ModelID'])
    op.create_unique_constraint('uq_AttributeValue_study_attribute_model', 'AttributeValue', ['StudyID', 'AttributeID', 'ModelID'])
    op.create_foreign_key(None, 'AttributeValue', 'Study', ['StudyID'], ['StudyID'])
    op.create_foreign_key(None, 'AttributeValue', 'Patient', ['PatientID'], ['PatientID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'AttributeValue', type_='foreignkey')
    op.drop_constraint(None, 'AttributeValue', type_='foreignkey')
    op.drop_constraint('uq_AttributeValue_study_attribute_model', 'AttributeValue', type_='unique')
    op.drop_constraint('uq_AttributeValue_patient_attribute_model', 'AttributeValue', type_='unique')
    op.drop_index('fk_AttributeValue_Study1_idx', table_name='AttributeValue')
    op.drop_index('fk_AttributeValue_Patient1_idx', table_name='AttributeValue')
    op.drop_column('AttributeValue', 'Laterality')
    op.drop_column('AttributeValue', 'StudyID')
    op.drop_column('AttributeValue', 'PatientID')
    # ### end Alembic commands ###
