"""CreatorTag table

Revision ID: 31212c7f33fd
Revises: d155d64d71b3
Create Date: 2025-09-15 17:50:00.424853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '31212c7f33fd'
down_revision: Union[str, None] = 'd155d64d71b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('CreatorTag',
    # sa.Column('TagID', sa.Integer(), nullable=False),
    # sa.Column('CreatorID', sa.Integer(), nullable=False),
    # sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    # sa.ForeignKeyConstraint(['CreatorID'], ['Creator.CreatorID'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['TagID'], ['Tag.TagID'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('TagID', 'CreatorID')
    # )
    # op.create_index('fk_CreatorTag_Creator1_idx', 'CreatorTag', ['CreatorID'], unique=False)
    # op.create_index('fk_CreatorTag_Tag1_idx', 'CreatorTag', ['TagID'], unique=False)
    op.drop_constraint('Annotation_ibfk_1', 'Annotation', type_='foreignkey')
    op.create_foreign_key(None, 'Annotation', 'Annotation', ['AnnotationReferenceID'], ['AnnotationID'], ondelete='CASCADE')
    op.drop_constraint('AnnotationTag_ibfk_3', 'AnnotationTag', type_='foreignkey')
    op.drop_constraint('AnnotationTag_ibfk_1', 'AnnotationTag', type_='foreignkey')
    op.create_foreign_key(None, 'AnnotationTag', 'Tag', ['TagID'], ['TagID'], ondelete='CASCADE')
    op.create_foreign_key(None, 'AnnotationTag', 'Annotation', ['AnnotationID'], ['AnnotationID'], ondelete='CASCADE')
    op.drop_constraint('fk_FormAnnotation_SubTask1', 'FormAnnotation', type_='foreignkey')
    op.drop_constraint('FormAnnotation_ibfk_1', 'FormAnnotation', type_='foreignkey')
    op.drop_constraint('fk_FormAnnotation_FormAnnotation1', 'FormAnnotation', type_='foreignkey')
    op.create_foreign_key(None, 'FormAnnotation', 'SubTask', ['SubTaskID'], ['SubTaskID'], ondelete='SET NULL')
    op.create_foreign_key(None, 'FormAnnotation', 'ImageInstance', ['ImageInstanceID'], ['ImageInstanceID'], ondelete='CASCADE')
    op.create_foreign_key(None, 'FormAnnotation', 'FormAnnotation', ['FormAnnotationReferenceID'], ['FormAnnotationID'], ondelete='CASCADE')
    op.drop_constraint('FormAnnotationTag_ibfk_2', 'FormAnnotationTag', type_='foreignkey')
    op.drop_constraint('FormAnnotationTag_ibfk_1', 'FormAnnotationTag', type_='foreignkey')
    op.create_foreign_key(None, 'FormAnnotationTag', 'FormAnnotation', ['FormAnnotationID'], ['FormAnnotationID'], ondelete='CASCADE')
    op.create_foreign_key(None, 'FormAnnotationTag', 'Tag', ['TagID'], ['TagID'], ondelete='CASCADE')
    op.drop_constraint('fk_ImageInstanceTag_Tag1', 'ImageInstanceTag', type_='foreignkey')
    op.drop_constraint('fk_ImageInstanceTag_ImageInstance1', 'ImageInstanceTag', type_='foreignkey')
    op.create_foreign_key(None, 'ImageInstanceTag', 'ImageInstance', ['ImageInstanceID'], ['ImageInstanceID'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ImageInstanceTag', 'Tag', ['TagID'], ['TagID'], ondelete='CASCADE')
    op.drop_constraint('fk_Patient_Project1', 'Patient', type_='foreignkey')
    op.create_foreign_key(None, 'Patient', 'Project', ['ProjectID'], ['ProjectID'], ondelete='CASCADE')
    op.drop_constraint('Segmentation_ibfk_5', 'Segmentation', type_='foreignkey')
    op.create_foreign_key(None, 'Segmentation', 'SubTask', ['SubTaskID'], ['SubTaskID'], ondelete='SET NULL')
    op.drop_constraint('SegmentationTag_ibfk_2', 'SegmentationTag', type_='foreignkey')
    op.drop_constraint('SegmentationTag_ibfk_1', 'SegmentationTag', type_='foreignkey')
    op.create_foreign_key(None, 'SegmentationTag', 'Tag', ['TagID'], ['TagID'], ondelete='CASCADE')
    op.create_foreign_key(None, 'SegmentationTag', 'Segmentation', ['SegmentationID'], ['SegmentationID'], ondelete='CASCADE')
    op.drop_constraint('Series_ibfk_1', 'Series', type_='foreignkey')
    op.create_foreign_key(None, 'Series', 'Study', ['StudyID'], ['StudyID'], ondelete='CASCADE')
    op.drop_constraint('fk_Study_Patient1', 'Study', type_='foreignkey')
    op.create_foreign_key(None, 'Study', 'Patient', ['PatientID'], ['PatientID'], ondelete='CASCADE')
    op.drop_constraint('fk_StudyTag_Study1', 'StudyTag', type_='foreignkey')
    op.drop_constraint('fk_StudyTag_Tag1', 'StudyTag', type_='foreignkey')
    op.create_foreign_key(None, 'StudyTag', 'Tag', ['TagID'], ['TagID'], ondelete='CASCADE')
    op.create_foreign_key(None, 'StudyTag', 'Study', ['StudyID'], ['StudyID'], ondelete='CASCADE')
    op.drop_constraint('fk_SubTask_Task1', 'SubTask', type_='foreignkey')
    op.create_foreign_key(None, 'SubTask', 'Task', ['TaskID'], ['TaskID'], ondelete='CASCADE')
    op.drop_constraint('fk_SubTaskImageLink_SubTask1', 'SubTaskImageLink', type_='foreignkey')
    op.drop_constraint('fk_SubTaskImageLink_ImageInstance1', 'SubTaskImageLink', type_='foreignkey')
    op.create_foreign_key(None, 'SubTaskImageLink', 'ImageInstance', ['ImageInstanceID'], ['ImageInstanceID'], ondelete='CASCADE')
    op.create_foreign_key(None, 'SubTaskImageLink', 'SubTask', ['SubTaskID'], ['SubTaskID'], ondelete='CASCADE')
    op.drop_column('Task', 'TaskStateID')
    # ### end Alembic commands ###
