"""add subtask image index

Revision ID: e4247389063f
Revises: 335c6bcc1fd8
Create Date: 2026-01-07 16:01:58.082555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4247389063f'
down_revision: Union[str, None] = '335c6bcc1fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_Patient_PatientIdentifier', 'Patient', ['PatientIdentifier'], unique=False)
    op.add_column('SubTaskImageLink', sa.Column('ImageIndex', sa.Integer(), nullable=False))
   
    # Populate ImageIndex for existing rows based on their natural SQL order within each SubTaskID
    # Uses MySQL variables to assign sequential indices (0, 1, 2, ...) preserving whatever order SQL returns
    # Initialize variables separately
    op.execute(sa.text("SET @idx := -1"))
    op.execute(sa.text("SET @prev_subtask := NULL"))
    # Update with sequential indices - resets to 0 for each new SubTaskID, increments otherwise
    op.execute(sa.text("""
        UPDATE SubTaskImageLink
        SET ImageIndex = IF(
            @prev_subtask = SubTaskID,
            @idx := @idx + 1,
            @idx := IF(@prev_subtask := SubTaskID, 0, 0)
        )
        ORDER BY SubTaskID
    """))
    
    # Now make the column non-nullable
    # MySQL requires the existing type when altering columns
    op.alter_column('SubTaskImageLink', 'ImageIndex',
                    existing_type=sa.Integer(),
                    nullable=False)
    
    # Add the unique constraint
    op.create_unique_constraint('uq_SubTaskImageLink_SubTask_ImageIndex', 'SubTaskImageLink', ['SubTaskID', 'ImageIndex'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_SubTaskImageLink_SubTask_ImageIndex', 'SubTaskImageLink', type_='unique')
    op.drop_column('SubTaskImageLink', 'ImageIndex')
    op.drop_index('ix_Patient_PatientIdentifier', table_name='Patient')
    # ### end Alembic commands ###
