"""image_storage_dates_public_id

Revision ID: 7b36f07198ee
Revises: a231a5374a36
Create Date: 2026-03-23 20:08:05.889645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7b36f07198ee'
down_revision: Union[str, None] = 'a231a5374a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ImageInstance', 'PublicID',
               existing_type=mysql.CHAR(length=8),
               type_=sa.CHAR(length=12),
               existing_nullable=False)
    op.drop_index('SourceInfoIDDatasetIdentifier_UNIQUE', table_name='ImageInstance')
    op.add_column('ImageStorage', sa.Column('DateInserted', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('ImageStorage', sa.Column('DateModified', sa.DateTime(), nullable=True))
    op.alter_column('SourceInfo', 'ThumbnailPath',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SourceInfo', 'ThumbnailPath',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.drop_column('ImageStorage', 'DateModified')
    op.drop_column('ImageStorage', 'DateInserted')
    op.create_index('SourceInfoIDDatasetIdentifier_UNIQUE', 'ImageInstance', ['DatasetIdentifier', 'SourceInfoID'], unique=True)
    op.alter_column('ImageInstance', 'PublicID',
               existing_type=sa.CHAR(length=12),
               type_=mysql.CHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
