"""image_storage

Revision ID: a231a5374a36
Revises: e4247389063f
Create Date: 2026-03-06 10:41:56.410658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from eyened_orm.image_instance import _make_public_id

# revision identifiers, used by Alembic.
revision: str = 'a231a5374a36'
down_revision: Union[str, None] = 'e4247389063f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('StorageBackend',
    sa.Column('StorageBackendID', sa.Integer(), nullable=False),
    sa.Column('Key', sa.String(length=256), nullable=False),
    sa.Column('Kind', sa.String(length=256), nullable=False),
    sa.Column('Config', mysql.JSON(), nullable=True, default=None),
    sa.PrimaryKeyConstraint('StorageBackendID'),
    sa.UniqueConstraint('Key', name='uq_StorageBackend_Key')
    )
    op.create_table('ImageStorage',
    sa.Column('ImageStorageID', sa.Integer(), nullable=False),
    sa.Column('ImageInstanceID', sa.Integer(), nullable=False),
    sa.Column('StorageBackendID', sa.Integer(), nullable=False),
    sa.Column('ObjectKey', sa.String(length=256), nullable=False),
    sa.Column('Hash', sa.BINARY(length=32), nullable=True),
    sa.Column('Checksum', sa.String(length=128), nullable=True),
    sa.Column('Format', sa.String(length=256), nullable=False),
    sa.Column('IsPrimary', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['ImageInstanceID'], ['ImageInstance.ImageInstanceID'], ),
    sa.ForeignKeyConstraint(['StorageBackendID'], ['StorageBackend.StorageBackendID'], ),
    sa.PrimaryKeyConstraint('ImageStorageID')
    )
    op.create_index(
        'ix_ImageStorage_ImageInstanceID_IsPrimary',
        'ImageStorage',
        ['ImageInstanceID', 'IsPrimary'],
        unique=False,
    )
    op.create_index(
        'ObjectKey_StorageBackendID_UNIQUE',
        'ImageStorage',
        ['ObjectKey', 'StorageBackendID'],
        unique=True,
    )
    op.add_column('ImageInstance', sa.Column('PublicID', sa.CHAR(length=8), nullable=True))
    op.alter_column('ImageInstance', 'SourceInfoID',
               existing_type=mysql.INTEGER(),
               nullable=True)

    connection = op.get_bind()
    image_instance = sa.Table(
        'ImageInstance',
        sa.MetaData(),
        sa.Column('ImageInstanceID', sa.Integer()),
        sa.Column('PublicID', sa.CHAR(length=8)),
    )
    total_needed = connection.execute(
        sa.select(sa.func.count(image_instance.c.ImageInstanceID)).where(
            image_instance.c.PublicID.is_(None)
        )
    ).scalar_one()

    public_ids: set[str] = set()
    while len(public_ids) < total_needed:
        public_ids.add(_make_public_id(length=8))

    public_id_iter = iter(public_ids)
    result = connection.execute(
        sa.select(image_instance.c.ImageInstanceID).where(
            image_instance.c.PublicID.is_(None)
        )
    )
    update_stmt = image_instance.update().where(
        image_instance.c.ImageInstanceID == sa.bindparam("b_ImageInstanceID")
    ).values(PublicID=sa.bindparam("public_id"))

    batch_size = 1000
    while True:
        rows = result.fetchmany(batch_size)
        if not rows:
            break
        params = [
            {
                "b_ImageInstanceID": image_id,
                "public_id": next(public_id_iter),
            }
            for (image_id,) in rows
        ]
        connection.execute(update_stmt, params)

    op.alter_column(
        'ImageInstance',
        'PublicID',
        existing_type=sa.CHAR(length=8),
        nullable=False,
    )

    
    op.create_unique_constraint(None, 'ImageInstance', ['PublicID'])
    op.drop_column('ImageInstance', 'FileChecksum')
    op.drop_column('ImageInstance', 'DataHash')
    op.drop_constraint('ModelSegmentation_ibfk_3', 'ModelSegmentation', type_='foreignkey')
    op.drop_column('ModelSegmentation', 'ReferenceSegmentationID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ModelSegmentation', sa.Column('ReferenceSegmentationID', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('ModelSegmentation_ibfk_3', 'ModelSegmentation', 'Segmentation', ['ReferenceSegmentationID'], ['SegmentationID'])
    op.add_column('ImageInstance', sa.Column('DataHash', mysql.TINYBLOB(), nullable=True))
    op.add_column('ImageInstance', sa.Column('FileChecksum', mysql.TINYBLOB(), nullable=True))
    op.alter_column('ImageInstance', 'SourceInfoID',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'ImageInstance', type_='unique')    
    op.drop_column('ImageInstance', 'PublicID')
    op.drop_index('ObjectKey_StorageBackendID_UNIQUE', table_name='ImageStorage')
    op.drop_index('ix_ImageStorage_ImageInstanceID_IsPrimary', table_name='ImageStorage')
    op.drop_table('ImageStorage')
    op.drop_table('StorageBackend')
    # ### end Alembic commands ###
